// <auto-generated />
using System;
using LIME.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LIME.Migrations
{
    [DbContext(typeof(LimeDbContext))]
    [Migration("20240809233934_AddAgentsTable")]
    partial class AddAgentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LIME.Database.Tables.Agents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activated");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Port")
                        .HasColumnType("longtext")
                        .HasColumnName("port");

                    b.HasKey("Id");

                    b.ToTable("agents");
                });

            modelBuilder.Entity("LIME.Database.Tables.AgentsPending", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_created");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_expire");

                    b.Property<string>("Secret")
                        .HasColumnType("longtext")
                        .HasColumnName("secret");

                    b.HasKey("Id");

                    b.ToTable("agents_pending");
                });
#pragma warning restore 612, 618
        }
    }
}
